### PR TITLE
Install the Syn jar

### PR DESCRIPTION
**Pull request by whikloj**
Resolves: https://github.com/Islandora-CLAW/CLAW/issues/777

### CODE REVIEW

**Comment by Natkeeran** [comment]
@whikloj 

My understanding is that `curl -i -XPUT "http://targethost:8080/fcrepo/rest/tester"` should fail after this PR.  That is not the case.  Even though the jar file is in the right place, the PUT request still goes through.

**Comment by Natkeeran** [comment]
@whikloj 

Can you pls have another look at this PR.  Thanks.

**Comment by whikloj** [comment]
@Natkeeran I think this is what was missing, but I am running into the blazegraph problems now. So I'll have to come back later to ensure this does what I think. Still not sure if this was in Tomcat and we lost it or if we never configured Syn correctly in the beginning.

**Comment by whikloj** [comment]
```
[whikloj@net227.lib.umanitoba.ca 15:56 ] 
[/sw/var/www/DAM2/claw-playbook] 
> curl -i http://localhost:8080/fcrepo/rest
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Cache-Control: private
Expires: Thu, 01 Jan 1970 00:00:00 UTC
ETag: W/"d3a7f9f7a5d0a2c5c24b40e61068ffee6175868e"
Last-Modified: Thu, 01 Mar 2018 20:13:44 GMT
Link: <http://www.w3.org/ns/ldp#Resource>;rel="type"
Link: <http://www.w3.org/ns/ldp#Container>;rel="type"
Link: <http://www.w3.org/ns/ldp#BasicContainer>;rel="type"
Accept-Patch: application/sparql-update
Accept-Post: text/turtle,text/rdf+n3,text/n3,application/rdf+xml,application/n-triples,application/ld+json,multipart/form-data,application/sparql-update
Allow: MOVE,COPY,DELETE,POST,HEAD,GET,PUT,PATCH,OPTIONS
Preference-Applied: return=representation
Vary: Prefer
Vary: Accept, Range, Accept-Encoding, Accept-Language
Content-Type: text/turtle;charset=utf-8
Content-Length: 3186
Date: Thu, 01 Mar 2018 21:56:46 GMT

@prefix schema:  <http://schema.org/> .
@prefix premis:  <http://www.loc.gov/premis/rdf/v1#> .
@prefix bf:  <http://id.loc.gov/ontologies/bibframe/> .
@prefix owl:  <http://www.w3.org/2002/07/owl#> .
@prefix pcdm:  <http://pcdm.org/models#> .
@prefix skos:  <http://www.w3.org/2004/02/skos/core#> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix acl:  <http://www.w3.org/ns/auth/acl#> .
@prefix pcdmfmt:  <http://pcdm.org/file-format-types#> .
@prefix ns002:  <http://fedora.info/definitions/v4/api-extension#> .
@prefix ns001:  <http://fedora.info/definitions/v4/service#> .
@prefix xsi:  <http://www.w3.org/2001/XMLSchema-instance> .
@prefix geo:  <http://www.w3.org/2003/01/geo/wgs84_pos#> .
@prefix xmlns:  <http://www.w3.org/2000/xmlns/> .
@prefix pcdmuse:  <http://pcdm.org/use#> .
@prefix xml:  <http://www.w3.org/XML/1998/namespace> .
@prefix pcdmwrks:  <http://pcdm.org/works#> .
@prefix rel:  <http://id.loc.gov/vocabulary/relators/> .
@prefix dcterms:  <http://purl.org/dc/terms/> .
@prefix event:  <http://fedora.info/definitions/v4/event#> .
@prefix prov:  <http://www.w3.org/ns/prov#> .
@prefix islandorarelsint:  <http://islandora.ca/ontology/relsint#> .
@prefix foaf:  <http://xmlns.com/foaf/0.1/> .
@prefix cc:  <http://creativecommons.org/ns#> .
@prefix ore:  <http://www.openarchives.org/ore/terms/> .
@prefix test:  <info:fedora/test/> .
@prefix fedoramodel:  <info:fedora/fedora-system:def/model#> .
@prefix gn:  <http://www.geonames.org/ontology#> .
@prefix pcdmrts:  <http://pcdm.org/rights#> .
@prefix islandorarelsext:  <http://islandora.ca/ontology/relsext#> .
@prefix dwc:  <http://rs.tdwg.org/dwc/terms/> .
@prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix fedora:  <http://fedora.info/definitions/v4/repository#> .
@prefix nfo:  <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#> .
@prefix ebucore:  <http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#> .
@prefix ldp:  <http://www.w3.org/ns/ldp#> .
@prefix iana:  <http://www.iana.org/assignments/relation/> .
@prefix xs:  <http://www.w3.org/2001/XMLSchema> .
@prefix config:  <info:fedoraconfig/> .
@prefix exif:  <http://www.w3.org/2003/12/exif/ns#> .
@prefix dc:  <http://purl.org/dc/elements/1.1/> .

<http://localhost:8080/fcrepo/rest/>
        fedora:lastModified            "2018-03-01T20:13:44.528Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
        rdf:type                       ldp:RDFSource ;
        rdf:type                       ldp:Container ;
        rdf:type                       ldp:BasicContainer ;
        fedora:writable                "true"^^<http://www.w3.org/2001/XMLSchema#boolean> ;
        rdf:type                       fedora:RepositoryRoot ;
        rdf:type                       fedora:Resource ;
        rdf:type                       fedora:Container ;
        ldp:contains                   <http://localhost:8080/fcrepo/rest/apix/extensions> ;
        ldp:contains                   <http://localhost:8080/fcrepo/rest/apix/ontologies> ;
        ldp:contains                   <http://localhost:8080/fcrepo/rest/apix/services> ;
        fedora:hasTransactionProvider  <http://localhost:8080/fcrepo/rest/fcr:tx> .

[whikloj@net227.lib.umanitoba.ca 15:56 ] 
[/sw/var/www/DAM2/claw-playbook] 
> curl -i http://localhost:8080/fcrepo/rest -XPOST
HTTP/1.1 401 Unauthorized
Server: Apache-Coyote/1.1
Content-Type: text/html;charset=utf-8
Content-Language: en
Content-Length: 1068
Date: Thu, 01 Mar 2018 21:56:51 GMT

<!DOCTYPE html><html><head><title>Apache Tomcat/8.0.32 (Ubuntu) - Error report</title><style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}.line {height: 1px; background-color: #525D76; border: none;}</style> </head><body><h1>HTTP Status 401 - Token authentication failed.</h1><div class="line"></div><p><b>type</b> Status report</p><p><b>message</b> <u>Token authentication failed.</u></p><p><b>description</b> <u>This request requires HTTP authentication.</u></p><hr class="line"><h3>Apache Tomcat/8.0.32 (Ubuntu)</h3></body></html>% 
```

**Comment by whikloj** [comment]
```
[whikloj@net227.lib.umanitoba.ca 15:56 ] 
[/sw/var/www/DAM2/claw-playbook] 
> curl -i http://localhost:8080/fcrepo/rest -XPOST -H"Authorization: Bearer islandora"
HTTP/1.1 201 Created
Server: Apache-Coyote/1.1
ETag: W/"bff5b826e8d977a56745f39eea8384aa128e5630"
Last-Modified: Thu, 01 Mar 2018 21:59:18 GMT
Location: http://localhost:8080/fcrepo/rest/e7/de/9b/28/e7de9b28-3e16-48d3-b01b-7c5f2a42944a
Content-Type: text/plain
Content-Length: 82
Date: Thu, 01 Mar 2018 21:59:18 GMT

http://localhost:8080/fcrepo/rest/e7/de/9b/28/e7de9b28-3e16-48d3-b01b-7c5f2a42944a
```

**Comment by whikloj** [comment]
@Natkeeran bump

**Comment by Natkeeran** [comment]
Works as expected.  

## Without authorization 
```
curl -i -XPUT "http://localhost:8080/fcrepo/rest/tester"
HTTP/1.1 401 Unauthorized
Server: Apache-Coyote/1.1
Content-Type: text/html;charset=utf-8
Content-Language: en
Content-Length: 1068
Date: Tue, 27 Mar 2018 17:58:10 GMT

<!DOCTYPE html><html><head><title>Apache Tomcat/8.0.32 (Ubuntu) - Error report</title><style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}.line {height: 1px; background-color: #525D76; border: none;}</style> </head><body><h1>HTTP Status 401 - Token authentication failed.</h1><div class="line"></div><p><b>type</b> Status report</p><p><b>message</b> <u>Token authentication failed.</u></p><p><b>description</b> <u>This request requires HTTP authentication.</u></p><hr class="line"><h3>Apache Tomcat/8.0.32 (Ubuntu)</h3></body></html>
```

## With authorization
```
curl -i -XPUT -H "Authorization: Bearer islandora"  "http://localhost:8080/fcrepo/rest/tester"
HTTP/1.1 201 Created
Server: Apache-Coyote/1.1
Cache-Control: private
Expires: Thu, 01 Jan 1970 00:00:00 UTC
ETag: W/"fa64549bf6bd850b8ebc27d31c3dfa71ae8d5f67"
Last-Modified: Tue, 27 Mar 2018 18:03:26 GMT
Location: http://localhost:8080/fcrepo/rest/tester
Content-Type: text/plain
Content-Length: 45
Date: Tue, 27 Mar 2018 18:03:26 GMT
```
http://localhost:8080/fcrepo/rest/testernat@natubuntu:~/Desktop/claw-playbook$ ^C

**Pull request merged**
